openapi: 3.0.0
x-stoplight:
  id: viyex0lwoda67
info:
  title: Authorization and Capture APIs
  version: 1.0.1
  description: |
    # Overview
    The Auth & Capture functionality is a two-step payment processing mechanism usually in
    Credit or Debit Card transactions. The **Auth** step verifies the availability of funds and reserves
    the amount, while the "Capture" step finalizes the transaction by transferring the reserved
    amount to the merchant after the customer requirement is fulfilled.
    Auth & Capture helps remove overheads for merchants and enhances customer satisfaction.
    Since funds are only captured when a service is successfully provided, the refund requests and
    customer disputes reduce drastically. Also, customers feel more confident knowing that they are
    only charged once requested services are fulfilled.

    This model also saves money for merchants by preventing unnecessary transaction fees and
    chargebacks associated with refunds. By capturing payments only for completed services,
    merchants avoid processing fees on failed or reversed transactions, reduce the need for
    customer support involvement, and improve overall operational efficiency. 


    ### Status:

    | S. No.| Event  | Txn. Status | Capture  Status  |
    | -- | ------- | --------------  | -----------|
    | 1. | initiateLink         | Pre-initiated     |  Pending |
    | 2. | Generate Access Key  |  Initiated        |  Pending |
    | 3. | Checkout             |  Initiated        |  Pending |
    | 4. | Checkout No Action   |  Bounced          |  Pending |
    | 5. | OTP Success          |  Pending          |  Authorized |
    | 6. | OTP No Reponse       |  Dropped          |  Dropped    |
    | 7. | Capture initiated by merchant  | Pending |  capture_pending |
    | 8. | Capture Failed       | Failure | Failure |
    | 9. | Capture Success       | Success| Success |
    | 10. | Capture Success is only executed when       | Pending | Authorized |



    ---

    ### Top Use Cases:


    | S. No.| Use Case  | Authorization | Capture    |
    | -- | ------- | --------------  | -----------|
    | 1. | E-commerce Platforms  | Funds are authorized at checkout.           |     Funds are captured only after the item is shipped / delivered. |
    | 2. | Hotel Bookings        | Funds are authorized at the time of booking.|     Captured upon check-in or checkout        |
    | 3. | Car Rentals           | Security deposit is authorized.             |     Deposit or rental fee is captured after return based on actual usage. |
    | 4. |Subscription Services  | Initial validation of the card.             |     Payment is captured after trial or as per billing cycle. |
    | 5. | Travel Bookings       | Funds are authorized at the time of booking.|     Funds are captured at travel initiation / completion. |

    ---

    ### Important Notes

    * If customer surcharge is ON - in such cases, merchant will have to incorporate the surcharge in the auth amount itself as capture amount cannot be greater than auth amount.
    * Merchant will have to initiate the capture within 4 working days of Auth. ( Capture timeline: T+4 )
    * Capture of amount less than or equal to auth amount is supported.
    * Multiple captures for single auth transaction is not supported.
    ---
servers:
  - description: 'Sandbox URL '
    url: 'https://testpay.easebuzz.in'
  - description: Production URL
    url: 'https://pay.easebuzz.in'
paths:
  /payment/initiateLink:
    post:
      summary: Initiate Payment API
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - key
                - txnid
                - amount
                - productinfo
                - firstname
                - phone
                - email
                - surl
                - furl
                - hash
                - payment_category
              properties:
                key:
                  type: string
                  description: 'This parameter is the unique Merchant Key provided by Easebuzz for your merchant account. The Merchant Key acts as the unique identifier (primary key) to identify a particular Merchant Account for our interpretation. While posting the data to us, you need to send this Merchant Key value.'
                  pattern: '^[a-zA-Z0-9_]{1,15}$'
                txnid:
                  type: string
                  description: This parameter is known as Transaction ID. It is the transaction reference number generated at your (Merchant’s) end. It is an identifier which you (merchant) would use to track a particular transaction. it is essential that you post us a unique transaction ID for every new transaction. **Please ensure that the txnid does not exceed 40 characters in length.**
                  pattern: '^[a-zA-Z0-9_\|\-\/]{1,40}$'
                amount:
                  type: number
                  example: '^[0-9.]*$'
                  description: 'This parameter should contain the payment amount of the particular transaction. Note: Please type-cast the amount to float type. **The maximum transaction amount limit is ₹ 99,99,999 by default.**'
                productinfo:
                  type: string
                  description: This parameter should contain a brief product description. It should be a string describing the product (The description type is entirely your choice). **The maximum length should not be greater than 45 characters.**
                  pattern: '^[a-zA-Z0-9-\s\|\-]{1,45}$'
                firstname:
                  type: string
                  description: |-
                    Name of the customers.
                    **The maximum allowed length for the customer's name is 150 characters.**
                  pattern: '^[a-zA-Z0-9&\-._ \()/,@]{1,150}$'
                phone:
                  type: integer
                  description: Phone number of the customer. **The maximum length is 20 digits.**
                  example: '^(\+\d{1,4}[-]?)?\d{5,20}$'
                email:
                  type: string
                  description: Email ID of the customer. **The maximum allowed length for the customer's email is 200 characters**.
                  pattern: '^(([^<>()\[\]\.,;:\s@"]+(\.[^<>()\[\]\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
                surl:
                  type: string
                  description: |-
                    Success URL - This parameter must contain the URL on which Easebuzz will redirect the final response if the transaction is successful. The response handling can then be done by you after redirection to this URL.
                    **The maximum length should not be greater than 2000 characters.**
                  pattern: 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F])){1,2000}$'
                furl:
                  type: string
                  description: |-
                    Failure URL - This parameter must contain the URL on which Easebuzz will redirect the final response if the transaction is failed. The response handling can then be done by you after redirection to this URL.
                    **The maximum length should not be greater than 2000 characters.**
                  pattern: 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F])){1,2000}$'
                hash:
                  type: string
                  description: 'Hash is a crucial parameter – used specifically to avoid any tampering during the transaction. This is sha512 encrypted string. Hash sequence: `key|txnid|amount|productinfo|firstname|email|||||||||||salt`'
                  pattern: '^[a-zA-Z0-9_]{64,128}$'
                payment_category:
                  type: string
                  description: Pass this parameter as `NCAP` for auth & capture payments.
                  x-stoplight:
                    id: isczgapl43x12
                request_flow:
                  type: string
                  description: 'For Seamless Payment, you have to pass this parameter with value as "SEAMLESS"'
                udf1:
                  type: string
                  description: 'User defined field 1 – This parameter has been made for you to keep any information corresponding to the transaction, which may be useful for you to keep in the database. UDF1-UDF7 fields are for this purpose only. It’s completely for your usage and you can post any string value in this parameter. udf1-udf7 are optional parameters and you may use them only if needed. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                udf2:
                  type: string
                  description: 'User defined field 2 – User Defined field 2. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                udf3:
                  type: string
                  description: 'User defined field 3 – User Defined field 3. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                udf4:
                  type: string
                  description: 'User defined field 4 – User Defined field 4. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                udf5:
                  type: string
                  description: 'User defined field 5 – User Defined field 5. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                udf6:
                  type: string
                  description: 'User defined field 6 – User Defined field 6. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                udf7:
                  type: string
                  description: 'User defined field 7 – User Defined field 7. Allowed characters : Letters, numbers, underscore, space,hyphen, dot(period)'
                  pattern: '^[a-zA-Z\.0-9/\\,\s_#@\-=+&]{1,300}$'
                address1:
                  type: string
                  description: 'This parameter is an optional parameter that can be used to pass the address. Allowed characters : Letters, numbers, comma, space, dot(period), hash, slash, hyphen, underscore.'
                  pattern: '^[a-zA-Z\.0-9/\,\s_#@()&|:-]{1,100}$'
                address2:
                  type: string
                  description: 'This parameter is an optional parameter that can be used to pass the address. Allowed characters : Letters, numbers, comma, space, dot(period), hash, slash, hyphen, underscore.'
                  pattern: '^[a-zA-Z\.0-9/\,\s_#@()&|:-]{1,100}$'
                city:
                  type: string
                  description: Customer City
                  pattern: '^[0-9a-zA-Z_.\s-]{1,50}$'
                state:
                  type: string
                  description: Customer State
                  pattern: '^[0-9a-zA-Z_.\s-]{1,50}$'
                country:
                  type: string
                  description: Customer Country
                  pattern: '^[0-9a-zA-Z_.\s-]{1,50}$'
                zipcode:
                  type: string
                  description: Customer Zipcode
                  pattern: '^[0-9]{0,6}$'
                show_payment_mode:
                  type: string
                  description: |-
                    Add the below details in show_payment_mode

                    Pass the require payment values with comma separated like below
                    show_payment_mode: ’DC,CC’

                    **Details:**

                    Payment Mode| Value | 
                    ---------|----------|
                     Credit Card| CC | 
                     Debit card| DC | 
                     
                    If Credit Card, Debit  are enabled for the Merchant and he requests to show the following modes: `CC, DC`
                    Then only a Credit Card and Debit Card will be allowed on the payment page.
                    Since this is the mode that is enabled for merchant and requested by merchant, Net Banking will not be visible because it was not enabled for Merchant by Easebuzz.

                    > **NOTE:** If show parameter mode is empty then all modes that are enabled for the Merchant will be visible.
                split_payments:
                  type: object
                  description: |-
                    If split payment feature is enabled for merchant account, then it is mandatory to pass this parameter. You can split the transaction amount across multiple split bank accounts mapped to your account.

                    **Expected Value**: {'label_of_bank1' : split_amount_in_rs, 'label_of_bank2': split_amount_in_rs}

                    **Split payment example**:
                    { "Easebuzztest 1": 11.0, "Easebuzztest  2": 1.0 }
                sub_merchant_id:
                  type: string
                  description: 'In case of aggregator setup, the submerchant unique id to initiate transaction towards the submerchant account. Mandatory if aggregator/submerchant setup is enabled.'
                  pattern: '^[a-zA-Z0-9\-]{0,15}$'
                unique_id:
                  type: string
                  x-stoplight:
                    id: c2wt7zknvqu7l
                  description: Pass the unique value in this parameter if you want to save customer card on Easebuzz checkout.
                  pattern: '''^[a-zA-Z0-9_]{0,40}$'''
            examples: {}
        description: ''
      responses:
        '200':
          description: "> **Note :** Once you receive the **Access Key** from the Initiate Payment API, Kindly use the below mentioned URL to load the hosted checkout page or [click here](https://docs.easebuzz.in/docs/payment-gateway/8q5xlsts1gv5a-integration-types) for different integration types. <br><br> **Sandbox URL:**\thttps://testpay.easebuzz.in/pay/access-key <br> **Production URL:**\thttps://pay.easebuzz.in/pay/access-key <br> **Example:** https://pay.easebuzz.in/pay/b7bf12baefeb6ecc27610290f3765aeebae9"
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    status: 1
                    data: d901bb89cac16e0c83213f4eb3d252ab7368a08d5d9706ae1ffad733f422aadd
                properties:
                  status:
                    type: integer
                  data:
                    type: string
                    description: The alphanumeric value of the data is known as the `Access Key`. It is valid for the next 15 minutes.
              examples:
                Success Response:
                  value:
                    status: 1
                    data: 114e574f3d63ca3a88f5f2c470869f926b147faa8a41c63f6381254ab28d26a9
                Error Response - 01:
                  value:
                    status: 0
                    error_desc: Invalid merchant key.
                    data: Parameter validation failed
                Error Response -02:
                  value:
                    status: 0
                    error_desc: hash mismatch.
                    data: Parameter validation failed
                Error Response - 03:
                  value:
                    status: 0
                    error_desc: Request Invalid for the merchant.
                    data: Parameter validation failed
      description: |
        Easebuzz payments work by creating request URLs which can accept payments. From your backend language, make a server-to-server call to our server(test or production) with the required parameters like the key, amount, transaction id. You can check out the complete list of mandatory and optional parameters in below table. Please ensure that all parameters are trimmed (leading and trailing white spaces are removed) before generating the hash.
        <br><br>**Note:**
         - Integrate [**Transaction Status API**](https://docs.easebuzz.in/docs/payment-gateway/f607brr7f8ek8-transaction-api-v2-1) and [**webhooks**](https://docs.easebuzz.in/docs/payment-gateway/587zy3v064so6-what-are-webhooks) to sync both systems statuses.
         - After receiving the response on the SURL or FURL, you must verify the hash using the reverse hash sequence to ensure data integrity.
         - Please note that **udf8**, **udf9**, and **udf10** should always be kept empty.
        **Hash sequence:** 
        ```
        key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5|udf6|udf7|udf8|udf9|udf10|salt
        ```
      operationId: post-payment-initiateLink
  /payment/v2/auth/capture/:
    post:
      summary: Capture API
      operationId: post-user
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Success Response:
                  value:
                    status: true
                    data:
                      deduction_percentage: '0.0'
                      net_amount_debit: '2.0'
                      cardCategory: NA
                      unmappedstatus: NA
                      addedon: '2025-05-23 14:02:45'
                      cash_back_percentage: '100.0'
                      bank_ref_num: '7480090109946149305910'
                      error_Message: Capture request received.
                      phone: '7620435055'
                      easepayid: E260*****OA9E
                      cardnum: XXXXXXXXXXXX8823
                      response_code: NA
                      auth_expiry_date: '2025-07-04 01:53:47'
                      capture_status: success/pending/authorized/dropped/captur_pending
                      payment_category: NCAP
                      payment_source: Easebuzz
                      card_type: Credit Card
                      mode: CC
                      error: Capture request received.
                      bankcode: NA
                      error_code: NA
                      upi_va: NA
                      name_on_card: NA
                      bank_name: NA
                      issuing_bank: NA
                      PG_TYPE: NA
                      amount: '2.0'
                      furl: 'https://pay.easebuzz.dev/seamless/response'
                      auth_ref_num: NA
                      productinfo: Test
                      auth_code: '668860'
                      email: yaman.bisen@easebuzz.in
                      status: pending
                      hash: e063ec0d61860a960ce8b349d6be385923bb7fa8bc9ee3c0f9f9ee02cdc1b410 9ada05617ab9c7cb2395495274100e1d20592fd7efb94716f7525827664185dd
                      firstname: Yaman
                      surl: 'https://pay.easebuzz.dev/seamless/response'
                      key: EZ*****RSA
                      merchant_logo: NA
                      udf10: ''
                      txnid: 20240415PG02
                      udf1: ''
                      udf3: ''
                      udf2: ''
                      udf5: ''
                      udf4: ''
                      udf7: ''
                      udf6: ''
                      udf9: ''
                      udf8: ''
                Error Response:
                  value:
                    status: false
                    data:
                      error_msg: 'Something went wrong.Error Code: GC0AC011'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - merchant_key
                - amount
                - txnid
                - checksum
              properties:
                merchant_key:
                  type: string
                  x-stoplight:
                    id: vk07xrskd3wcq
                  description: Unique Merchant Key provided by Easebuzz for your merchant account.
                amount:
                  type: number
                  x-stoplight:
                    id: n16jbi5vwb8ye
                  description: 'The amount value, that you want to capture.'
                txnid:
                  type: string
                  x-stoplight:
                    id: 72m3etq8nf0vo
                  description: Unique Easebuzz Id generated by Easebuzz. You will receive this value in the transaction response.
                checksum:
                  type: string
                  x-stoplight:
                    id: dgqjsq662in4a
                  description: 'This is sha512 encrypted string. And hash sequence is mentioned above. Hash sequence: `merchant_key|amount|txnid|salt`'
                split_payments:
                  type: string
                  x-stoplight:
                    id: ocstmlni7781r
                  description: |-
                    **Note:** Split labels, if updated in capture API then same will be updated in system and old labels will
                    be deleted.<br>
                    Split of the transaction amount based on the labels configured for split on Easebuzz.

                    Example: {"Label_1": 11.0, "Label_2": 1.0}
            examples:
              Example 1:
                value: {}
        description: ''
      description: |-
        **UseCase**: Capture an authorized transaction.

        **Description**: This API is used to send a capture request to Easebuzz for an authorized transaction. It
        accepts all the required parameters and returns a pending or failure response, which is then used to further
        process the transaction.

        > ***Note:*** Capture can be initiated within T+4 of the authorization. Post this, the authorization will be considered void and the amount blocked / reserved in user’s account will be freed.
        ---
        1. After authorization, merchant has to fulfil the services requested by the customer.
        2. On successful fulfilment, merchant to initiate the Capture request for the same Auth transaction with Easebuzz within the pre-defined time limit and with Capture amount less than or equal to the Auth amount.
        3. On receiving the Capture request, Easebuzz to do the necessary checks and initiate the capture request with Acquirer referencing the original Auth transaction.
        4. Acquirer routes the debit request to Issuer through Card Network. As the requested amount is already authorized for debit, Issuer debits the user account directly.
        5. Issuer marks the transaction as Captured and updates the acquirer which in turn sends the response to Easebuzz.
        6. Easebuzz then updates merchant about the transaction (Capture) status which then further updates the user.
        ---

        **Hash sequence:** 
        ```
        merchant_key|amount|txnid|salt
        ```
      x-stoplight:
        id: 4b98sx2z183ms
      x-internal: false
    parameters: []
  /payment/v1/auth/reversal/:
    post:
      summary: Void API
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
                    x-stoplight:
                      id: 28vljnqrl0zro
              examples:
                Success Response:
                  value:
                    status: true
                    msg: Auth reversal processed successfully
                    txnid: TEST_TXN_123456
                    reversal_status: success
                    amount: '1000.00'
                Error Response:
                  value:
                    status: false
                    error: This is initiated for auto-reversal / Reversal amount is 0.
                    txnid: E2601050RQ1SB4
      operationId: post-payment-v1-auth-reversal
      x-stoplight:
        id: j51586t0spdcm
      x-internal: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - merchant_key
                - txnid
                - checksum
              properties:
                merchant_key:
                  type: string
                  x-stoplight:
                    id: f4gjkjkk2r9b7
                  description: Merchant key provided by Easebuzz.
                txnid:
                  type: string
                  x-stoplight:
                    id: cymyz3et4n9s0
                  description: Easebuzz transaction ID shared in the authorization response.
                checksum:
                  type: string
                  x-stoplight:
                    id: 7a4b5g0rmcy5r
                  description: 'Hash is a crucial parameter – used specifically to avoid any tampering during the transaction. This is sha512 encrypted string. Hash sequence: `merchant_key|txnid|salt`'
                reason:
                  type: string
                  x-stoplight:
                    id: y5es6sc4rd54l
                  description: |
                    Reason to void the transaction.
        description: ''
      description: |-
        **UseCase**: To void (unblock) an authorized transaction if not captured


        **Description**: This API is used to initiate the Void request with Easebuzz for any authorized transaction
        which merchant is not willing to Capture. It accepts all the required parameters and returns a success or
        failure response.

        ---
        1. Refunds can only be done for the captured amount.
        2. Merchant has to initiate the request with Easebuzz either through dashboard or Refund API.
        3. Once request is received, Easebuzz will check the refund details and merchant payout equal to the refund amount will be put on hold.
        4. Easebuzz will then initiate the refund request with acquirer which will get it processed through Issuer bank.
        5. Once acquirer confirms back of the refund status, the same will be shared with merchant.
        6. Merchant can then update the user of the refund status.
        7. Standard refund TAT is 7 working days from the date of refund initiation.
        ---

        > **Note:** There could be multiple use-cases of Refund / un-blocking of captured and un-captured amount:


        | S. No.| Auth  | Capture | Refund Type   | Refund Type Description | Workflow |
        | -- | ------- | --------------  | ----------- | ------------------ | ------------ |
        | 1. | Success | Full Capture    | Refund requested     | full refund requested after capture                                  | Standard refund workflow |
        | 2. | Success | Partial Capture | Partial Auto unblock | auto-unblock of un-captured amount after capture period              | auto-initiated after T+4 |
        | 3. | Success | Partial Capture | Partial Auto unblock | request for un-blocking the un-captured amount during capture period | Void API + configuration to be done at bank’s end |
        | 4. | Success | Partial Capture | Refund requested     | request for refund of partially captured amount                      | Standard refund workflow |
        | 5. | Success | No capture      | Auto unblock         | auto unblock of full amount after capture  period                    | auto-initiated after T+4 |
        | 6. | Success | No capture      | Un-block requested   | request for un-blocking the un-captured amount during capture period | Void API + configuration to be done at bank’s end |


        **Hash sequence:** 
        ```
        merchant_key|txnid|salt
        ```
components:
  schemas: {}
x-internal: false
